getwd()
setwd("C:/Users/PRINCE SINHA/Documents")
file.create("Reva.txt")
data = read.table("Reva.txt")
View(data)
print(data)
file.create("Rev1.csv")
data = read.csv("Reva1.csv")
print(data)
View(data)
print(data$salary)
View(data)
print(max(data$salary))
print(min(data$salary))
print(mean(data$salary))
print(mode(data$salary))
print(median(data$salary))
print(SD(data$salary))
print(var(data$salary))
print(summary(data$salary))
print(head(data$salary))
print(tail(data$salary))
rperson = subset(data,salary == max(data$salary))
print(rperson)
View(rperson)
rperson = subset(data,salary == min(data$salary))
print(rperson)
View(rperson)

rperson = subset(data,dept == "IT")
print(rperson)
View(rperson)

rperson = subset(data,dept == "Finance")
print(rperson)
View(rperson)

rperson = subset(data,dept == "IT" & salary >= 600)
print(rperson)
View(rperson)

rperson = subset(data,start_date >= "2014-01-01")
print(rperson)
View(rperson)

rperson = subset(data,start_date >= "2014")
print(rperson)
View(rperson)

rperson = subset(data,dept = "Finance",start_date >= "2014")
print(rperson)
View(rperson)

